package com.axis.jgbbackend.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import org.springframework.data.mongodb.core.mapping.Document

@Document("autoApplication")
@JsonIgnoreProperties(ignoreUnknown = true)
class AutoApplication(
    applicationDate: String? = null,
    applicationReferenceId: String? = null,
    applicationStateLogs: List<MutableMap<*, *>>? = null,
    val assetPriceBreakupsVariationLimit: MutableMap<*, *>? = null,
    channelAttribution: MutableMap<*, *>? = null,
    cibilCheckConsent: MutableMap<*, *>? = null,
    val crmLeadDetails: MutableMap<*, *>? = null,
    customerEditable: MutableMap<*, *>? = null,
    customerId: String? = null,
    customerType: String? = null,
    demogDetails: MutableMap<*, *>? = null,
    gtmParams: MutableMap<*, *>? = null,
    hunterResult: HunterResult? = null,
    insuranceDetails: MutableMap<*, *>? = null,
    insurancePremium: MutableMap<*, *>? = null,
    journeyCode: String? = null,
    knockOff: MutableMap<*,*>? = null,
    kycResponse: MutableMap<*, *>? = null,
    loanOffer: LoanOffer? = null,
    val loanOfferRequest: MutableMap<*, *>? = null,
    loanParameters: MutableMap<*, *>? = null,
    val loanRequest: MutableMap<*, *>? = null,
    mailingAddressPincodeMapping: MutableMap<*, *>? = null,
    maxServiceableEMI: MutableMap<*, *>? = null,
    metaData: MutableMap<*, *>? = null,
    mlpCustomerIdentifier: MutableMap<String, String>? = null,
    val offerSanctionLetter: MutableMap<*, *>? = null,
    offerType: String? = null,
    val opsHumanTaskDetails: OpsHumanTaskDetails? = null,
    val parallelRiskToggle: MutableMap<*, *>? = null,
    preApprovedOffer: MutableMap<*, *>? = null,
    productCode: String? = null,
    sangamResult: MutableMap<*, *>? = null,
    val selectedAsset: MutableMap<*, *>? = null,
    val selectedLocationAndPan: MutableMap<*, *>? = null,
    selectedMailingAddress: MutableMap<*, *>? = null,
    val selectedMerchant: MutableMap<*, *>? = null,
    source: MutableMap<*, *>? = null,
    state: String? = null,
    submissionTime: String? = null,
    updatedEmailAddress: MutableMap<*, *>? = null,
    utmParams: MutableMap<*, *>? = null
): CustomerApplication(
    applicationReferenceId,
    applicationDate,
    applicationStateLogs,
    channelAttribution,
    cibilCheckConsent,
    customerEditable,
    customerId,
    customerType,
    demogDetails,
    gtmParams,
    hunterResult,
    insuranceDetails,
    insurancePremium,
    journeyCode,
    knockOff,
    kycResponse,
    loanOffer,
    loanParameters,
    mailingAddressPincodeMapping,
    maxServiceableEMI,
    metaData,
    mlpCustomerIdentifier,
    offerType,
    preApprovedOffer,
    productCode,
    sangamResult,
    selectedMailingAddress,
    source,
    state,
    submissionTime,
    updatedEmailAddress,
    utmParams
)