package com.axis.jgbbackend.model

data class BreakdownXX(
    val amount: String,
    val appScoreBand: AppScoreBandXX,
    val assetCategory: String,
    val base: String,
    val category: String,
    val channel: String,
    val cibilHit: String,
    val date: DateXX,
    val displayName: String,
    val feeType: String,
    val gst: String,
    val loan: LoanXX,
    val mScoreBand: MScoreBandXX,
    val maxTimeSpentDuringPrevious: String,
    val name: String,
    val noOfJourneyStarts: String,
    val percentage: String,
    val productCode: String,
    val promoId: String,
    val screenReachedPrevious: String,
    val segment: String,
    val serviceCharge: String,
    val source: String,
    val state: String,
    val status: String,
    val strategy: String,
    val tenure: TenureXXX,
    val uniqueId: String,
    val value: Int
)