package com.axis.jgbbackend.model

open class CustomerApplication (
    val applicationReferenceId: String? = null,
    val applicationDate: String? = null,
    val applicationStateLogs: List<MutableMap<*,*>>? = null,
    val channelAttribution: MutableMap<*,*>? = null,
    val cibilCheckConsent: MutableMap<*,*>? = null,
    val customerEditable: MutableMap<*,*>? = null,
    val customerId: String? = null,
    val customerType: String? = null,
    val demogDetails: MutableMap<*,*>? = null,
    val gtmParams: MutableMap<*,*>? = null,
    val hunterResult: MutableMap<*,*>? = null,
    val insuranceDetails: MutableMap<*,*>? = null,
    val insurancePremium: MutableMap<*,*>? = null,
    val journeyCode: String? = null,
    val knockOff: MutableMap<*,*>? = null,
    val kycResponse: MutableMap<*,*>? = null,
    val loanOffer: LoanOffer? = null,
    val loanParameters: MutableMap<*,*>? = null,
    val mailingAddressPincodeMapping: MutableMap<*,*>? = null,
    val maxServiceableEMI: MutableMap<*,*>? = null,
    val metaData: MutableMap<*,*>? = null,
    val mlpCustomerIdentifier: MutableMap<String,String>? = null,
    val offerType: String? = null,
    val preApprovedOffer: MutableMap<*,*>? = null,
    val productCode: String? = null,
    val sangamResult: MutableMap<*,*>? = null,
    val selectedMailingAddress: MutableMap<*,*>? = null,
    val source: MutableMap<*,*>? = null,
    val state: String? = null,
    val submissionTime: String? = null,
    val updatedEmailAddress: MutableMap<*,*>? = null,
    val utmParams: MutableMap<*,*>? = null
)