package com.axis.jgbbackend.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import org.springframework.data.mongodb.core.mapping.Document

@Document("personalApplication")
@JsonIgnoreProperties(ignoreUnknown = true)
class PersonalApplication(
    applicationReferenceId: String? = null,
    val activeSavingsAccounts: MutableMap<*,*>? = null,
    applicationDate: String? = null,
    applicationStateLogs: List<MutableMap<*,*>>? = null,
    channelAttribution: MutableMap<*,*>? = null,
    cibilCheckConsent: MutableMap<*,*>? = null,
    customerEditable: MutableMap<*,*>? = null,
    customerId: String? = null,
    customerType: String? = null,
    demogDetails: MutableMap<*,*>? = null,
    val disbursementDetails: MutableMap<*,*>? = null,
    val feedback: MutableMap<*,*>? = null,
    val finnoneAppId: MutableMap<*,*>? = null,
    val fraudDetails: MutableMap<*,*>? = null,
    gtmParams: MutableMap<*,*>? = null,
    hunterResult: MutableMap<*,*>? = null,
    val incomeDetails: MutableMap<*,*>? = null,
    insuranceDetails: MutableMap<*,*>? = null,
    insurancePremium: MutableMap<*,*>? = null,
    journeyCode: String? = null,
    knockOff: MutableMap<*,*>? = null,
    kycResponse: MutableMap<*,*>? = null,
    loanOffer: LoanOffer? = null,
    loanParameters: MutableMap<*,*>? = null,
    mailingAddressPincodeMapping: MutableMap<*,*>? = null,
    maxServiceableEMI: MutableMap<*,*>? = null,
    metaData: MutableMap<*,*>? = null,
    mlpCustomerIdentifier: MutableMap<String,String>? = null,
    offerType: String? = null,
    val otpValidation: MutableMap<*,*>? = null,
    val personalWhatsAppOptIn: MutableMap<*,*>? = null,
    preApprovedOffer: MutableMap<*,*>? = null,
    val preferredDisbursementAccount: MutableMap<*,*>? = null,
    productCode: String? = null,
    val repaymentData: MutableMap<*,*>? = null,
    sangamResult: MutableMap<*,*>? = null,
    val selectedLoanDetails: MutableMap<*,*>? = null,
    selectedMailingAddress: MutableMap<*,*>? = null,
    source: MutableMap<*,*>? = null,
    state: String? = null,
    submissionTime: String? = null,
    val termAndConditionPdf: MutableMap<*,*>? = null,
    updatedEmailAddress: MutableMap<*,*>? = null,
    utmParams: MutableMap<*,*>? = null
): CustomerApplication(
    applicationReferenceId,
    applicationDate,
    applicationStateLogs,
    channelAttribution,
    cibilCheckConsent,
    customerEditable,
    customerId,
    customerType,
    demogDetails,
    gtmParams,
    hunterResult,
    insuranceDetails,
    insurancePremium,
    journeyCode,
    knockOff,
    kycResponse,
    loanOffer,
    loanParameters,
    mailingAddressPincodeMapping,
    maxServiceableEMI,
    metaData,
    mlpCustomerIdentifier,
    offerType,
    preApprovedOffer,
    productCode,
    sangamResult,
    selectedMailingAddress,
    source,
    state,
    submissionTime,
    updatedEmailAddress,
    utmParams
)